import { index, jsonb, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Schema conventions:
 *  - uuid primary keys, generated by the database
 *  - timestamps are `timestamptz`, always UTC, never a bare `timestamp`
 *  - every table carries created_at and updated_at
 *  - new columns arrive nullable; see the expand/contract rule in CLAUDE.md
 */
export const users = pgTable('users', {
  id: uuid('id').primaryKey().defaultRandom(),
  email: text('email').notNull().unique(),
  name: text('name'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

/**
 * Appointment requests submitted from the public site.
 *
 * PRIVACY — read before changing this table.
 *
 * `reason` holds health information under the Privacy Act 1988. An organisation
 * providing a health service and holding health information is covered by the
 * Act regardless of turnover; the small business exemption does not apply. NSW
 * providers are additionally subject to the Health Records and Information
 * Privacy Act 2002.
 *
 * Consequences encoded here:
 *  - health information is confined to ONE column, so retention and redaction
 *    have a single target
 *  - `consentAt` is NOT NULL: a row cannot exist without recorded consent
 *  - `sourceHash` is a salted hash, never a raw IP
 *  - `purgeAfter` is NOT NULL so every row has an expiry from the moment it is
 *    written
 */
export const bookingRequests = pgTable(
  'booking_requests',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    reference: text('reference').notNull().unique(),
    status: text('status', { enum: ['pending', 'contacted', 'scheduled', 'declined'] })
      .notNull()
      .default('pending'),
    serviceSlug: text('service_slug').notNull(),
    practitioner: text('practitioner'),
    fullName: text('full_name').notNull(),
    phone: text('phone'),
    email: text('email'),
    preferred: jsonb('preferred').$type<string[]>().notNull().default([]),
    /** HEALTH INFORMATION. Never log, echo or notify on this column. */
    reason: text('reason'),
    consentAt: timestamp('consent_at', { withTimezone: true }).notNull(),
    sourceHash: text('source_hash').notNull(),
    idempotencyKey: text('idempotency_key').unique(),
    purgeAfter: timestamp('purge_after', { withTimezone: true }).notNull(),
    contactedAt: timestamp('contacted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    index('booking_requests_status_created').on(t.status, t.createdAt),
    index('booking_requests_purge').on(t.purgeAfter),
    index('booking_requests_source_window').on(t.sourceHash, t.createdAt),
  ],
);

export type BookingRequestRow = typeof bookingRequests.$inferSelect;
export type NewBookingRequestRow = typeof bookingRequests.$inferInsert;
